const data = {
  products: [
    {
      id: "1",
      name: "Free Shirt",
      category: "Shirts",
      slug: "free-shirt",
      image: "/images/shirt1.jpg",
      price: 400,
      brand: "Nike",
      rating: 4.5,
      numReviews: 40,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      id: "2",
      name: "Fit Shirt",
      category: "fit-shirt",
      slug: "free-shirt",
      image: "/images/shirt2.jpg",
      price: 500,
      brand: "Adidas",
      rating: 5,
      numReviews: 13,
      countInStock: 23,
      description: "A popular shirt",
    },
    {
      id: "3",
      name: "Slim Shirt",
      category: "Shirts",
      slug: "slim-shirt",
      image: "/images/shirt3.jpg",
      price: 700,
      brand: "Raymond",
      rating: 3.5,
      numReviews: 15,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      id: "4",
      name: "Goalf Pants",
      category: "pants",
      slug: "goalf-pants",
      image: "/images/pants1.jpg",
      price: 450,
      brand: "Oliver",
      rating: 2.5,
      numReviews: 19,
      countInStock: 20,
      description: "Smart looking pants",
    },
    {
      id: "5",
      name: "Fit Pants",
      category: "Pants",
      slug: "fit-pants",
      image: "/images/pants2.jpg",
      price: 400,
      brand: "Zara",
      rating: 4.5,
      numReviews: 25,
      countInStock: 20,
      description: "A popular pants",
    },
    {
      id: "6",
      name: "Classic Pants",
      category: "Pants",
      slug: "classic-pants",
      image: "/images/pants3.jpg",
      price: 400,
      brand: "Casely",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular pants",
    },
  ],
};
export default data;
